#测试环境
server:
  port: 80
spring:
  profiles: test
  mvc:
    static-path-pattern: /**
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

# 百度对应的配置
baidu:
  #  百度人脸识别配置
  face:
    appId: ""
    appKey: ""
    secretKey: ""

#   匹配度达到多少算合格
face:
  # 人脸识别度达到多少算合格
  matchScore: 90
  # 身份验证闸值
  verifyScore: 80
  #  key
  appKey: "faceApp"
  #  秘钥
  appSecret: "UQFopX1r0ysV2Xp1QYv03cHjBsYmKvDY"
  #  盐值
  salt: "sgkj311"


